#!/usr/bin/env python3
# -*- coding: utf-8 -*-

UPYUN_BUCKET = ''
UPYUN_USERNAME = ''
UPYUN_PASSWORD = ''
EMAIL_REDIS_LIST_KEY = ''
REDIS_LIST_KEY = ''
DATA_DB_USER = ''
DATA_DB_PASSWORD = ''
DB_HOST = ''
DB_HOST_PORT = 3306
DATA_DB_NAME = ''
IS_NEED_EMAIL_ALERT = True
TCP_CONNECTION_TIMEOUT = 10
